package com.xworkz.collections.boot;

import java.util.Collection;
import java.util.LinkedList;

public class CollectionRunner {

	public static void main(String[] args) 
	{
		String sweet1 = "Rasmalai";
		String sweet2 = "Jamun";
		String sweet3 = "Jilebi";
		String sweet4 = "Cova";
		String sweet5 = "Kesribath";
		String sweet6 = "Jangier";
		String sweet7 = "Kaju Burfi";
		String sweet8 = "Mango Burfi";
		String sweet9 = "Boondhi";
		String sweet10 = "Rasgulla";
		String sweet11 = "Kaju urfi";
		String sweet12 = "Mysorepak";
		String sweet13 = "Peda";
		String sweet14 = "Sonpapudi";
		
		Collection<String> collection = new LinkedList<String>();
		collection.add(sweet14);
		collection.add(sweet13);
		collection.add(sweet12);
		collection.add(sweet11);
		collection.add(sweet10);
		collection.add(sweet9);
		collection.add(sweet8);
		collection.add(sweet7);
		collection.add(sweet6);
		collection.add(sweet5);
		collection.add(sweet4);
		collection.add(sweet3);
		collection.add(sweet2);
		collection.add(sweet1);
		System.out.println(collection.size() + "sweets");
		collection.clear();
		System.out.println("After clear..");
		System.out.println(collection.size());
		
		
		System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
		String currencies1 = "Dollar";
		String currencies2 = "Euro";
		String currencies3 = "East Timor";
		String currencies4 = "Ecuador";
		String currencies5 = "Panama";
		String currencies6 = "Palau";
		String currencies7 = "Zimbabwe";
		String currencies8 = "Andorra";
		String currencies9 = "Francs";
		String currencies10 = "Belize Dollar";
		String currencies11 = "Boliviano";
		String currencies12 = "Pula";
		String currencies13 = "Renminbi ";
		String currencies14 = "Comoro Franc";
		String currencies15 = "Cuban Peso";
		String currencies16 = "Australian Dollar";
		String currencies17 = "Danish Kroner";
		String currencies18 = "Nakfa";
		String currencies19 = "Ethiopian Birr";
		String currencies20 = "pound";
		String currencies21 = "CFP Franc";
		String currencies22 = "Franc";
		String currencies23 = "Dalasi";
		String currencies24 = "Cedi";
		String currencies25 = "Forint";
		String currencies26 = "Indian Rupee";
		
		Collection<String> collection2 = new LinkedList<String>();
		collection2.add(currencies26);
		collection2.add(currencies25);
		collection2.add(currencies24);
		collection2.add(currencies23);
		collection2.add(currencies22);
		collection2.add(currencies21);
		collection2.add(currencies20);
		collection2.add(currencies19);
		collection2.add(currencies18);
		collection2.add(currencies17);
		collection2.add(currencies16);
		collection2.add(currencies15);
		collection2.add(currencies14);
		collection2.add(currencies13);
		collection2.add(currencies12);
		collection2.add(currencies11);
		collection2.add(currencies10);
		collection2.add(currencies9);
		collection2.add(currencies8);
		collection2.add(currencies7);
		collection2.add(currencies6);
		collection2.add(currencies5);
		collection2.add(currencies4);
		collection2.add(currencies3);
		collection2.add(currencies2);
		collection2.add(currencies1);
		System.out.println("Adding currencies : "+collection2.size());
		collection2.clear();
		System.out.println("After clear...");
		System.out.println(collection2.size());
		
		System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
		String coupoun1 = "Ways to Earn";
		String coupoun2 = "RetailCurve";
		String coupoun3 = "Auctionscoupon";
		String coupoun4 = "AllPlus Coupons";
		String coupoun5 = "Sylinn Coupons";
		String coupoun6 = "Coupon Savvy";
		String coupoun7 = "Cards N More";
		String coupoun8 = "MingCoupon";
		String coupoun9 = "Coupon Buddy";
		String coupoun10 = "Peak Coupon";
		String coupoun11 = "BrownSaver";
		String coupoun12 = "Coupon Tree";
		
		Collection<String> collection3 = new LinkedList<String>();
		collection3.add(coupoun12);
		collection3.add(coupoun11);
		collection3.add(coupoun10);
		collection3.add(coupoun9);
		collection3.add(coupoun8);
		collection3.add(coupoun7);
		collection3.add(coupoun6);
		collection3.add(coupoun5);
		collection3.add(coupoun4);
		collection3.add(coupoun3);
		collection3.add(coupoun2);
		collection3.add(coupoun1);
		System.out.println("coupoun :" + collection3.size());
		collection3.clear();
		System.out.println("After clear....");
		System.out.println(collection3.size());
		
		System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
		
		String bike1 = "TVS";
		String bike2 = "Honda";
		String bike3 = "Royal Enfield";
		String bike4 = "Hero";
		String bike5 = "Yamaha";
		String bike6 = "Splender";
		String bike7 = "Scooty";
		String bike8 = "dio";
		String bike9 = "Hero Destini 125";
		String bike10 = "Pulser";
		String bike11 = "Apache";
		String bike12 = "KTM";
		String bike13 = "Suzuki Gixxer";
		String bike14 = "TVS Jupiter";
		
		Collection<String> bike = new LinkedList<String>();
		bike.add(bike1);
		bike.add(bike2);
		bike.add(bike3);
		bike.add(bike4);
		bike.add(bike5);
		bike.add(bike6);
		bike.add(bike7);
		bike.add(bike8);
		bike.add(bike9);
		bike.add(bike10);
		bike.add(bike11);
		bike.add(bike12);
		bike.add(bike13);
		bike.add(bike14);
		System.out.println("Adding bikes :" +bike.size());
		bike.clear();
		System.out.println("After clear...");
		System.out.println(bike.size());
		
		System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
		
		String mall1 = "GT Mall";
		String mall2 = "Orian Mall";
		String mall3 = "Mantri Mall";
		String mall4 = "Garuda Mall";
		String mall5 = "UB City";
		String mall6 = "Koramangala Mall";
		String mall7 = "Phoenix Markt";
		String mall8 = "Fourm Mall";
		String mall9 = "LULU Mall";
		String mall10 = "VR Mall";
		String mall11 = "Gopalan Mall";
		String mall12 = "DLF Mall";
		String mall13= "Sarath City Mall";
		String mall14 = "Z Square Mall";
		String mall15 = "HiLITE Mall";
		String mall16 = "World Trade Park Mall";
		String mall17 = "Elante Mall";
		String mall18 = "Esplanade Mall";
		String mall19 = "Ambience Mall";
		String mall20 = "Viviana Mall";
		String mall21 = "Select CITYWALK Mall";
		String mall22 = "Ahmedabad One Mall";
		String mall23 = "GIP Mall";
		String mall24 = "Pacific Mall";
		String mall25 = "Grand Venice Mall";
		String mall26 = "Royal Meenakshi Mall";
		String mall27 = "Avenues Mall";
		String mall28 = "Aventura Mall";
		String mall29 = "Eatons Mall";
		String mall30 = "DLF Emporior Mall";
		String mall31 = "Alto Palermo Mall";
		String mall32 = "Zhengjia Plaza Mall";
		String mall33 = "Wynn Esplanade Mall";
		String mall34 = "Grand Indonesia Mall";
		String mall35 = "Greenbelt  Mall";
		String mall36 = "Festival  Mall";
		String mall37 = "Bawadi  Mall";
		String mall38 = "Aricanduva  Mall";
		String mall39 = "Pitt Street Mall";
		String mall40 = "Wafi  Mall";
		
		Collection<String> mall = new LinkedList<String>();
		mall.add(mall1);
		mall.add(mall2);
		mall.add(mall3);
		mall.add(mall4);
		mall.add(mall5);
		mall.add(mall6);
		mall.add(mall7);
		mall.add(mall8);
		mall.add(mall9);
		mall.add(mall10);
		mall.add(mall11);
		mall.add(mall12);
		mall.add(mall13);
		mall.add(mall14);
		mall.add(mall15);
		mall.add(mall16);
		mall.add(mall17);
		mall.add(mall18);
		mall.add(mall19);
		mall.add(mall20);
		mall.add(mall21);
		mall.add(mall22);
		mall.add(mall23);
		mall.add(mall24);
		mall.add(mall25);
		mall.add(mall26);
		mall.add(mall27);
		mall.add(mall28);
		mall.add(mall29);
		mall.add(mall30);
		mall.add(mall31);
		mall.add(mall32);
		mall.add(mall33);
		mall.add(mall34);
		mall.add(mall35);
		mall.add(mall36);
		mall.add(mall37);
		mall.add(mall38);
		mall.add(mall39);
		mall.add(mall40);
		System.out.println("Adding Mall : "+mall.size());
		mall.clear();
		System.out.println("After clear....");
		System.out.println(mall.size());
		
		
	}

}
