package com.xworkz.collections.dto;

public enum weaponType 
{
	SHORTRANGEWEAPONS , LONGRANGEWEAPONS , FIREARMS , BIOLOGICALWEAPONS , CHEMICALWEAPONS , NUCLEARWEAPONS , COMBATWEAPONS , MISSILES , ROCKETS , SEMIAUTOMIC , SIEGEWEAPONS , AUTOMIC 
}
